version: "3.9"
services:
  instagram-analyzer:
    build:
      context: .
    networks:
      - n8n_network
    ports:
      - "8000:8000"

  n8n:
    image: n8nio/n8n
    networks:
      - n8n_network
    ports:
      - "5678:5678"

networks:
  n8n_network:
    external: true
